sharding:
  db1:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharding_00?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&failOverReadOnly=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dbname: sharding_00
  db2:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharding_01?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&failOverReadOnly=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dbname: sharding_01
  db3:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharding_02?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&failOverReadOnly=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dbname: sharding_02

spring:
  jpa:
    show-sql: true
  properties:
    hibernate.dialect: com.biligame.access.common.dialect.MySQLDialectUTF8
    hibernate.format_sql: false
    hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    ## hibernate entity ???
#    hibernate.enable_lazy_load_no_trans: true